import turtle
import random
scn=turtle.Screen()
scn.bgcolor("Yellow")
babis=turtle.Turtle()
turtle.title("FLags")

points = 0
life = 3



def France():
    babis.pendown()
    babis.fillcolor("blue")
    babis.begin_fill()
    babis.forward(50)
    babis.left(90)
    babis.forward(100)
    babis.left(90)
    babis.forward(50)
    babis.left(90)
    babis.forward(100)
    babis.end_fill()

    babis.penup()
    babis.left(90)
    babis.forward(50)
    babis.pendown()
    babis.fillcolor("white")
    babis.begin_fill()
    babis.forward(50)
    babis.left(90)
    babis.forward(100)
    babis.left(90)
    babis.forward(50)
    babis.left(90)
    babis.forward(100)
    babis.end_fill()

    babis.penup()
    babis.left(90)
    babis.forward(50)
    babis.pendown()
    babis.fillcolor("red")
    babis.begin_fill()
    babis.forward(50)
    babis.left(90)
    babis.forward(100)
    babis.left(90)
    babis.forward(50)
    babis.end_fill()

def Italy():
    babis.pendown()
    babis.fillcolor("green")
    babis.begin_fill()
    babis.forward(50)
    babis.left(90)
    babis.forward(100)
    babis.left(90)
    babis.forward(50)
    babis.left(90)
    babis.forward(100)
    babis.end_fill()

    babis.penup()
    babis.left(90)
    babis.forward(50)
    babis.pendown()
    babis.fillcolor("white")
    babis.begin_fill()
    babis.forward(50)
    babis.left(90)
    babis.forward(100)
    babis.left(90)
    babis.forward(50)
    babis.left(90)
    babis.forward(100)
    babis.end_fill()

    babis.penup()
    babis.left(90)
    babis.forward(50)
    babis.pendown()
    babis.fillcolor("red")
    babis.begin_fill()
    babis.forward(50)
    babis.left(90)
    babis.forward(100)
    babis.left(90)
    babis.forward(50)
    babis.end_fill()

def Ukraine():
    babis.pendown()
    babis.fillcolor("blue")
    babis.begin_fill()
    babis.forward(200)
    babis.right(90)
    babis.forward(50)
    babis.right(90)
    babis.forward(200)
    babis.right(90)
    babis.forward(50)
    babis.end_fill()
    babis.penup()
    babis.left(180)
    babis.forward(50)
    babis.pendown()
    babis.fillcolor("yellow")
    babis.begin_fill()
    babis.forward(50)
    babis.left(90)
    babis.forward(200)
    babis.left(90)
    babis.forward(50)
    babis.end_fill()

def Armenia():
    babis.pendown()
    babis.fillcolor("red")
    babis.begin_fill()
    babis.forward(300)
    babis.right(90)
    babis.forward(50)
    babis.right(90)
    babis.forward(300)
    babis.right(90)
    babis.forward(50)
    babis.end_fill()
    babis.penup()

    babis.left(180)
    babis.forward(50)
    babis.pendown()
    babis.fillcolor("blue")
    babis.begin_fill()
    babis.forward(50)
    babis.left(90)
    babis.forward(300)
    babis.left(90)
    babis.forward(50)
    babis.left(90)
    babis.forward(300)
    babis.end_fill()

    babis.penup()
    babis.left(90)
    babis.forward(50)
    babis.pendown()
    babis.fillcolor("orange")
    babis.begin_fill()
    babis.forward(50)
    babis.left(90)
    babis.forward(300)
    babis.left(90)
    babis.forward(50)
    babis.end_fill()

def Nigeria():
    babis.pendown()
    babis.fillcolor("green")
    babis.begin_fill()
    babis.forward(50)
    babis.left(90)
    babis.forward(100)
    babis.left(90)
    babis.forward(50)
    babis.left(90)
    babis.forward(100)
    babis.end_fill()

    babis.penup()
    babis.left(90)
    babis.forward(50)
    babis.pendown()
    babis.fillcolor("white")
    babis.begin_fill()
    babis.forward(50)
    babis.left(90)
    babis.forward(100)
    babis.left(90)
    babis.forward(50)
    babis.left(90)
    babis.forward(100)
    babis.end_fill()

    babis.penup()
    babis.left(90)
    babis.forward(50)
    babis.pendown()
    babis.fillcolor("green")
    babis.begin_fill()
    babis.forward(50)
    babis.left(90)
    babis.forward(100)
    babis.left(90)
    babis.forward(50)
    babis.end_fill()\

def Japan():
    babis.pendown()
    babis.fillcolor("white")
    babis.begin_fill()
    babis.forward(300)
    babis.right(90)
    babis.forward(150)
    babis.right(90)
    babis.forward(300)
    babis.right(90)
    babis.forward(150)
    babis.end_fill()

    babis.penup()
    babis.left(180)
    babis.forward(110)
    babis.left(90)
    babis.forward(150)
    babis.fillcolor("red")
    babis.begin_fill()
    babis.circle(35)
    babis.end_fill()

def Finland():
    babis.pendown()
    babis.fillcolor("white")
    babis.begin_fill()
    babis.forward(300)
    babis.right(90)
    babis.forward(150)
    babis.right(90)
    babis.forward(300)
    babis.right(90)
    babis.forward(150)
    babis.end_fill()

    babis.right(90)
    babis.forward(100)
    babis.right(90)
    babis.fillcolor("blue")
    babis.begin_fill()
    babis.forward(50)
    babis.right(90)
    babis.forward(100)
    babis.left(90)
    babis.forward(20)
    babis.left(90)
    babis.forward(100)
    babis.right(90)
    babis.forward (80)
    babis.left(90)
    babis.forward(20)
    babis.left(90)
    babis.forward(80)
    babis.right(90)
    babis.forward (180)
    babis.left(90)
    babis.forward(20)
    babis.left(90)
    babis.forward(180)
    babis.right(90)
    babis.forward(50)
    babis.end_fill()

def Sweden():
    babis.pendown()
    babis.fillcolor("blue")
    babis.begin_fill()
    babis.forward(300)
    babis.right(90)
    babis.forward(150)
    babis.right(90)
    babis.forward(300)
    babis.right(90)
    babis.forward(150)
    babis.end_fill()

    babis.right(90)
    babis.forward(100)
    babis.right(90)
    babis.fillcolor("yellow")
    babis.begin_fill()
    babis.forward(50)
    babis.right(90)
    babis.forward(100)
    babis.left(90)
    babis.forward(20)
    babis.left(90)
    babis.forward(100)
    babis.right(90)
    babis.forward(80)
    babis.left(90)
    babis.forward(20)
    babis.left(90)
    babis.forward(80)
    babis.right(90)
    babis.forward(180)
    babis.left(90)
    babis.forward(20)
    babis.left(90)
    babis.forward(180)
    babis.right(90)
    babis.forward(50)
    babis.left(90)
    babis.forward(30)
    babis.end_fill()

def Norway():
    babis.pendown()
    babis.fillcolor("red")
    babis.begin_fill()
    babis.forward(300)
    babis.right(90)
    babis.forward(150)
    babis.right(90)
    babis.forward(300)
    babis.right(90)
    babis.forward(150)
    babis.end_fill()

    babis.penup()
    babis.right(90)
    babis.pendown()
    babis.fillcolor("white")
    babis.begin_fill()
    babis.forward(75)
    babis.right(90)
    babis.forward(45)
    babis.right(90)
    babis.forward(75)
    babis.left(90)
    babis.forward(30)
    babis.left(90)
    babis.forward(75)
    babis.right(90)
    babis.forward(75)
    babis.left(90)
    babis.forward(30)
    babis.left(90)
    babis.forward(75)
    babis.right(90)
    babis.forward(195)
    babis.left(90)
    babis.forward(30)
    babis.left(90)
    babis.forward(195)
    babis.right(90)
    babis.forward(45)
    babis.left(90)
    babis.forward(30)
    babis.end_fill()

    babis.pendown()
    babis.right(180)
    babis.forward(10)
    babis.pendown()
    babis.fillcolor("blue")
    babis.begin_fill()
    babis.right(90)
    babis.forward(55)
    babis.right(90)
    babis.forward(85)
    babis.left(90)
    babis.forward(10)
    babis.left(90)
    babis.forward(85)
    babis.right(90)
    babis.forward(85)
    babis.left(90)
    babis.forward(10)
    babis.left(90)
    babis.forward(85)
    babis.right(90)
    babis.forward(205)
    babis.left(90)
    babis.forward(10)
    babis.left(90)
    babis.forward(205)
    babis.right(90)
    babis.forward(55)
    babis.left(90)
    babis.forward(10)
    babis.end_fill()

def Greece():
    babis.pendown()
    babis.fillcolor("blue")
    babis.begin_fill()
    babis.forward(300)
    babis.right(90)
    babis.forward(20)
    babis.right(90)
    babis.forward(300)
    babis.right(90)
    babis.forward(40)
    babis.right(90)
    babis.end_fill()

    babis.pendown()
    babis.fillcolor("white")
    babis.begin_fill()
    babis.forward(300)
    babis.right(90)
    babis.forward(20)
    babis.right(90)
    babis.forward(300)
    babis.right(90)
    babis.forward(40)
    babis.right(90)
    babis.end_fill()

    babis.pendown()
    babis.fillcolor("blue")
    babis.begin_fill()
    babis.forward(300)
    babis.right(90)
    babis.forward(20)
    babis.right(90)
    babis.forward(300)
    babis.right(90)
    babis.forward(40)
    babis.right(90)
    babis.end_fill()

    babis.pendown()
    babis.fillcolor("white")
    babis.begin_fill()
    babis.forward(300)
    babis.right(90)
    babis.forward(20)
    babis.right(90)
    babis.forward(300)
    babis.right(90)
    babis.forward(20)
    babis.end_fill()

    babis.penup()
    babis.forward(20)
    babis.pendown()
    babis.fillcolor("blue")
    babis.begin_fill()
    babis.right(90)
    babis.forward(300)
    babis.right(90)
    babis.forward(20)
    babis.right(90)
    babis.forward(300)
    babis.right(90)
    babis.forward(20)
    babis.end_fill()

    babis.fillcolor("white")
    babis.begin_fill()
    babis.forward(20)
    babis.right(90)
    babis.forward(300)
    babis.right(90)
    babis.forward(20)
    babis.right(90)
    babis.forward(300)
    babis.right(90)
    babis.forward(20)
    babis.end_fill()

    babis.fillcolor("blue")
    babis.begin_fill()
    babis.forward(20)
    babis.right(90)
    babis.forward(300)
    babis.right(90)
    babis.forward(20)
    babis.right(90)
    babis.forward(300)
    babis.right(90)
    babis.forward(20)
    babis.end_fill()

    babis.fillcolor("white")
    babis.begin_fill()
    babis.forward(20)
    babis.right(90)
    babis.forward(300)
    babis.right(90)
    babis.forward(20)
    babis.right(90)
    babis.forward(300)
    babis.right(90)
    babis.forward(20)
    babis.end_fill()

    babis.fillcolor("blue")
    babis.begin_fill()
    babis.forward(20)
    babis.right(90)
    babis.forward(300)
    babis.right(90)
    babis.forward(20)
    babis.right(90)
    babis.forward(300)
    babis.right(90)
    babis.forward(20)
    babis.end_fill()

    babis.pendown()
    babis.right(90)
    babis.forward(40)
    babis.fillcolor("white")
    babis.begin_fill()
    babis.right(90)
    babis.forward(40)
    babis.right(90)
    babis.forward(40)
    babis.left(90)
    babis.forward(20)
    babis.left(90)
    babis.forward(40)
    babis.right(90)
    babis.forward(40)
    babis.left(90)
    babis.forward(20)
    babis.left(90)
    babis.forward(40)
    babis.right(90)
    babis.forward(40)
    babis.left(90)
    babis.forward(20)
    babis.left(90)
    babis.forward(40)
    babis.right(90)
    babis.forward(40)
    babis.left(90)
    babis.forward(20)
    babis.end_fill()


    babis.left(90)
    babis.fillcolor("blue")
    babis.begin_fill()
    babis.forward(40)
    babis.right(90)
    babis.forward(40)
    babis.right(90)
    babis.forward(40)
    babis.end_fill()

    babis.right(180)
    babis.penup()
    babis.forward(60)
    babis.pendown()
    babis.fillcolor("blue")
    babis.begin_fill()
    babis.forward(40)
    babis.left(90)
    babis.forward(40)
    babis.left(90)
    babis.forward(40)
    babis.left(90)
    babis.forward(40)
    babis.end_fill()

#cross

    babis.penup()
    babis.right(180)
    babis.forward(60)
    babis.pendown()
    babis.fillcolor("blue")
    babis.begin_fill()
    babis.forward(40)
    babis.right(90)
    babis.forward(40)
    babis.right(90)
    babis.forward(40)
    babis.right(90)
    babis.forward(40)
    babis.end_fill()

    babis.penup()
    babis.forward(60)
    babis.pendown()
    babis.fillcolor("blue")
    babis.begin_fill()
    babis.right(90)
    babis.forward(40)
    babis.right(90)
    babis.forward(40)
    babis.right(90)
    babis.forward(40)
    babis.right(90)
    babis.forward(40)
    babis.end_fill()

flags = [France, Italy, Ukraine, Armenia, Nigeria, Japan, Finland, Sweden, Norway, Greece]

while life>0 and len(flags)>0:
    babis.reset()
    babis.speed(200)
    flag = random.choice(flags)
    flag()
    answer = input("Guess the flag")

    if answer == flag.__name__:
        print("You guessed the flag right!")
        points = points+1
        print("Points:",points)
        print("life:",life)
        flags.remove(flag)
    else:
        print("You guessed the flag wrong, try again!")
        life = life-1
        print("Points:", points)
        print("life:", life)

print("Game over!")











#France()
#Italy()
#Ukraine()
#Armenia()
#Nigeria()
#Japan()
#Finland()
#Sweden()
#Norway()
#Greece()

turtle.done()